package com.temelio.controller;

import java.util.UUID;

import com.temelio.api.GrandSubmissionsAPI;
import com.temelio.model.domain.GrandSubmission;
import com.temelio.service.GrandSubmissionsService;
import jakarta.annotation.security.RolesAllowed;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.core.Response;

@RolesAllowed("ADMIN")
public class GrandSubmissionsController implements GrandSubmissionsAPI {

	private final GrandSubmissionsService grandSubmissionsService;

	public GrandSubmissionsController(final GrandSubmissionsService grandSubmissionsService) {
		this.grandSubmissionsService = grandSubmissionsService;
	}


	/**
	 * @return a list of submissions for a nonprofit
	 */
	@Override
	@GET
	@Path("/{id}/submissions")
	public Response getGrandSubmissions(@PathParam("id") final UUID nonProfitId) {
		return this.grandSubmissionsService.getGrandSubmissions(nonProfitId);
	}

	/**
	 * Creates a new nonprofit (id is autogenerated)
	 */
	@Override
	@POST
	@Path("/{id}/submissions")
	public Response addGrandSubmission(@PathParam("id") final UUID nonProfitId, final GrandSubmission grandSubmission) {
		return this.grandSubmissionsService.addGrandSubmission(nonProfitId, grandSubmission);
	}

	@Override
	@GET
	@Path("/{id}/submissions/{gSId}")
	public Response getGrandSubmission(@PathParam("id") final UUID nonProfitId, @PathParam("gSId") final UUID grandSubmissionId) {
		return this.grandSubmissionsService.getGrandSubmission(nonProfitId, grandSubmissionId);
	}


	/**
	 * @retuns a submission by id for a nonprofit
	 * @param: Non Profit id
	 * @param: submission id
	 */
	@Override
	@PUT
	@Path("/{id}/submissions/{gSId}")
	public Response updateGrandSubmission(@PathParam("id") final UUID nonProfitId,
	                                      @PathParam("gSId") final UUID grandSubmissionId,
	                                      final GrandSubmission grandSubmission) {
		return this.grandSubmissionsService.updateGrandSubmission(nonProfitId, grandSubmissionId, grandSubmission);
	}

	/**
	 * @return a list of submissions for all nonprofits
	 */
	@Override
	@GET
	@Path("/submissions")
	public final Response getAllGrandSubmissions() {
		return this.grandSubmissionsService.getAllGrandSubmissions();
	}

}