package com.temelio.api;

import java.util.UUID;

import com.temelio.model.domain.GrandSubmission;
import jakarta.annotation.security.RolesAllowed;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

@Path("/nonprofits")
@Produces(MediaType.APPLICATION_JSON)
@RolesAllowed("ADMIN")
public interface GrandSubmissionsAPI {

	/**
	 * @return a list of submissions for a nonprofit
	 */
	@GET
	@Path("/{id}/submissions")
	public Response getGrandSubmissions(@PathParam("id") @NotNull @Valid final UUID nonProfitId);

	/**
	 * Creates a new nonprofit (id is autogenerated)
	 */
	@POST
	@Valid
	@Path("/{id}/submissions")
	public Response addGrandSubmission(@PathParam("id") @NotNull @Valid final UUID nonProfitId,
	                                   @NotNull @Valid final GrandSubmission grandSubmission);

	/**
	 * Creates a new nonprofit (id is autogenerated)
	 */
	@GET
	@Valid
	@Path("/{id}/submissions")
	public Response getGrandSubmission(@PathParam("id") @NotNull @Valid final UUID nonProfitId,
	                                   @PathParam("gSId") @NotNull @Valid final UUID grandSubmissionId);

	/**
	 * @retuns a submission by id for a nonprofit
	 * @param: Non Profit id
	 * @param: submission id
	 */
	@PUT
	@Valid
	@Path("/{id}/submissions/{gSId}")
	public Response updateGrandSubmission(@PathParam("id") @NotNull @Valid final UUID nonProfitId,
	                                      @PathParam("gSId") @NotNull @Valid final UUID grandSubmissionId,
	                                      @NotNull @Valid final GrandSubmission grandSubmission);

	/**
	 * @return a list of submissions for all nonprofits
	 */
	@GET
	@Path("/submissions")
	public Response getAllGrandSubmissions();

}