package com.temelio.api;

import java.util.UUID;

import com.temelio.model.domain.NonProfit;
import jakarta.annotation.security.RolesAllowed;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

@Path("/nonprofits")
@Produces(MediaType.APPLICATION_JSON)
@RolesAllowed("ADMIN")
public interface NonProfitsAPI {

	/**
	 * @return the list of all nonprofits
	 */
	@GET
	public Response getNonProfits();

	/**
	 * Creates a new nonprofit (id is autogenerated)
	 */
	@POST
	public Response addNonProfit(final NonProfit nonProfit);

	/**
	 * @retuns a nonprofit by id
	 * @param: Non Profit id
	 */
	@GET
	@Path("/{id}")
	public Response getNonProfit(@PathParam("id") @NotNull @Valid final UUID nonProfitId);

	/**
	 * Updates a nonprofit by id
	 *
	 * @param: Non Profit id
	 */
	@PUT
	@Path("/{id}")
	public Response updateNonProfit(@PathParam("id") @NotNull @Valid final UUID nonProfitId,
	                                @NotNull @Valid final NonProfit nonProfit);
}